import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import "remixicon/fonts/remixicon.css";
import ClientOnly from "../components/clientOnlyComponent/ClientOnlyComponent"; // Import Client Wrapper
import Navbar from "../components/navbar/Navbar"; // Normal Import
import Footer from "../components/footer/Footer"; // Normal Import
import LetsChatSection from "../components/letsChat/LetsChat"; // Normal Import

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Anas N",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative antialiased`}>
        {/* ✅ Only Wrap Client Components */}
        <ClientOnly>
          <Navbar />
        </ClientOnly>

        <div className="absolute top-0 left-0 w-full h-full -z-10">
          {/* <ClientOnly> */}
            <LetsChatSection />
          {/* </ClientOnly> */}
        </div>

        {children}

        {/* <ClientOnly> */}
          <Footer />
        {/* </ClientOnly> */}
      </body>
    </html>
  );
}
